# Series

In [2]:
from pandas import Series, DataFrame
import pandas as pd

In [4]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index([u'd', u'b', u'a', u'c'], dtype='object')

In [9]:
obj2['d']

4

In [10]:
obj2['d'] = 6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [11]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [12]:
obj2>0

d     True
b     True
a    False
c     True
dtype: bool

In [13]:
'b' in obj2

True

In [14]:
'e' in obj2

False

In [15]:
#data contained in a dict can be used to create a Series
sdata = {'Ohio':35000, 'Texas':71000,'Oregon':160000,'Utah':5000}
obj3 = Series(sdata)
obj3

Ohio       35000
Oregon    160000
Texas      71000
Utah        5000
dtype: int64

In [16]:
states = ['California','Ohio','Oregon','Texas']
obj4 = Series(sdata, index=states)
obj4

California         NaN
Ohio           35000.0
Oregon        160000.0
Texas          71000.0
dtype: float64

In [19]:
pd.isnull?


Data Frame

In [22]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada'],
    'year': [2000,2001,2002,2001,2002],
    'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [23]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [24]:
frame2 = DataFrame(data, columns=['year','state','pop','debt'],
                  index = ['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [25]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [26]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [28]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [29]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [31]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [33]:
import numpy as np
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [35]:
data = DataFrame(np.arange(16).reshape((4,4)),
                index=['Ohio','Colorado','Utah','New York'],
                columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [36]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [37]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [38]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [39]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [40]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [41]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [42]:
data.ix[1:4]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [43]:
arr = np.arange(12.).reshape((3,4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [44]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [45]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [47]:
frame = DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),
                 index=['Utah','Ohio','Texas','Oregon'])
series = frame.ix[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [48]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [49]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [51]:
series2 = Series(range(3), index=['b','e','f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [52]:
series3 = frame['d']
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [53]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'),
                 index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    0.379578 -0.213989 -0.665795
Ohio    0.839161  1.507626 -0.723223
Texas  -2.267857 -0.864321  0.121394
Oregon -0.216767 -0.279200  1.522253

In [56]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    3.107017
d    2.371946
e    2.245476
dtype: float64

In [57]:
frame.apply(f,axis=1)

Utah      1.045374
Ohio      2.230848
Texas     2.389251
Oregon    1.801454
dtype: float64

In [58]:
def f(x):
    return Series([x.min(), x.max()], index=['min','max'])

frame.apply(f)


b         d         e
min -2.267857 -0.864321 -0.723223
max  0.839161  1.507626  1.522253

In [59]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah     0.38  -0.21  -0.67
Ohio     0.84   1.51  -0.72
Texas   -2.27  -0.86   0.12
Oregon  -0.22  -0.28   1.52

In [60]:
frame['e'].map(format)

Utah      -0.67
Ohio      -0.72
Texas      0.12
Oregon     1.52
Name: e, dtype: object

In [63]:
df = DataFrame([[1.4, np.nan],[7.1,-4.5],[np.nan, np.nan],[0.75, -1.3]],
              index= ['a','b','c','d'],
              columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [64]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [65]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [68]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [69]:
df.idxmax()

one    b
two    d
dtype: object

In [70]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [71]:
df.describe()

C:\Anaconda2\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%         NaN       NaN
50%         NaN       NaN
75%         NaN       NaN
max    7.100000 -1.300000

In [72]:
import pandas.io.data as web

all_data = {}
for ticker in ['AAPL','IBM','MSFT','GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker)
    
price = DataFrame({tic: data['Adj Close']
                  for tic, data in all_data.iteritems()})

volume = DataFrame({tic: data['Volume']
                   for tic, data in all_data.iteritems()})


C:\Anaconda2\lib\site-packages\pandas\io\data.py:35: FutureWarning: 
The pandas.io.data module is moved to a separate package (pandas-datareader) and will be removed from pandas in a future version.
After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.
  FutureWarning)


In [73]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-07  0.001493 -0.002291 -0.007713  0.001039
2016-10-10  0.017447  0.014011  0.008672  0.004152
2016-10-11  0.002154 -0.003652 -0.014202 -0.014645
2016-10-12  0.008942  0.003920 -0.003230 -0.001399
2016-10-13 -0.003068 -0.010113 -0.003694 -0.003327

In [74]:
returns.MSFT.corr(returns.IBM)

0.50427846997985237

In [75]:
returns.MSFT.cov(returns.IBM)

8.9431006315765786e-05

In [76]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.408310  0.387224  0.391094
GOOG  0.408310  1.000000  0.407615  0.466767
IBM   0.387224  0.407615  1.000000  0.504278
MSFT  0.391094  0.466767  0.504278  1.000000

In [77]:
returns.cov()


AAPL      GOOG       IBM      MSFT
AAPL  0.000278  0.000108  0.000078  0.000096
GOOG  0.000108  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000096  0.000108  0.000089  0.000215

In [78]:
returns.corrwith(returns.IBM)

AAPL    0.387224
GOOG    0.407615
IBM     1.000000
MSFT    0.504278
dtype: float64